In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5]=100   #gives value 100 for first 5 indexes

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr=np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr=arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:]=99      #chanages the actual data also 

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy=arr.copy()   #nakes a copy which dont changes

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy[:]=100

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr   #there is no change in arrray

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_2d=np.array([[5,10,15],[4,45,6],[6,78,8]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [ 4,  5,  6],
       [ 6, 78,  8]])

In [32]:
arr_2d[0] #gets whole row

array([ 5, 10, 15])

In [33]:
arr_2d[0][0]    #takes perfect array item

5

In [34]:
arr_2d[2][0]

6

In [36]:
arr_2d[2,1]      #index 2 column 1

78

In [37]:
arr_2d[:2,1:]   #sub seections

array([[10, 15],
       [ 5,  6]])

In [41]:
arr=np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 5     #conditional

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr>5

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]   #only prints trues

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr>5]    #same as up

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr<3]

array([1, 2])

In [51]:
arr_2d=np.arange(50).reshape(5,10)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
arr_2d[3:,:2]

array([[30, 31],
       [40, 41]])