In [2]:
my_list=[1,2,3]

In [3]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_math=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5)) #tuples

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))   #matrix rep

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)   #generates linearly spaced vectors.here 10 is no of points
                      #here 10 is no of points we want.

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [5]:
np.eye(4)    #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.rand(5)

array([0.67821644, 0.18764026, 0.70268078, 0.78668959, 0.23070319])

In [7]:
np.random.rand(5,5)

array([[0.14136683, 0.07223875, 0.47185083, 0.5506178 , 0.3565031 ],
       [0.45497152, 0.25845669, 0.24903985, 0.56294627, 0.54413956],
       [0.07228022, 0.07418928, 0.42887256, 0.85520161, 0.4838677 ],
       [0.37752115, 0.28404169, 0.87945029, 0.34045596, 0.96833511],
       [0.58897802, 0.95077842, 0.85267095, 0.93038513, 0.40775806]])

In [8]:
np.random.randn(2)

array([ 0.66457901, -0.04878901])

In [11]:
np.random.randint(1,100) #one random number between one and hundred

9

In [13]:
np.random.randint(1,100,10)  #will get 10 random numbers

array([ 4, 13,  4, 65, 62,  3, 70,  5, 41, 85])

In [17]:
arr=np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr=np.random.randint(0,50,10)

In [20]:
ranarr

array([26, 24, 40, 17, 20, 46,  3, 17,  2,  2])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

46

In [25]:
ranarr.min()

2

In [26]:
ranarr.argmax()   #to get maximum array index

5

In [27]:
ranarr.argmin()

8

In [28]:
arr.shape

(25,)

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr=arr.reshape(5,5)

In [34]:
arr.shape

(5, 5)

In [35]:
arr.dtype

dtype('int32')

In [36]:
from numpy.random import randint

In [37]:
randint(2,10)

3